### ISSUE TITLE
Nav component should accept an extra prop to set the background color of the renderIcon area

### ISSUE THREAD

**Issue by donatoaguirre24** [siriwatknp/mui-layout#15]
In the following example, the whole navbar had the same background color.

![Alt Text](https://media.giphy.com/media/1BgIQWDxSNQHZS0HiN/giphy.gif)

I'm unable to reproduce it because there isn't a prop that allows changing the background of the renderIcon area for the Nav component. I can change the color of the icon but not the color of the button that wraps it.

I'm getting the following result:

![image](https://user-images.githubusercontent.com/20030075/61730880-b0666400-ad50-11e9-84c4-24a32238b5d6.png)

It would be great if you can add this prop to set the background, the border-color and the background-color on hover for the Button that uses classes.collapseButton in src/components/Nav.js

**Comment by elitan** [comment]
I think if we can set `z-index: 1201;` to `MuiDrawer-paperAnchorDockedLeft` I think we can have the left navigation to go over the header.

 ![image](https://user-images.githubusercontent.com/331818/62041956-2eb58100-b1fd-11e9-9951-6c5f34f80f68.png)

@siriwatknp What do you think?

**Comment by siriwatknp** [comment]
@donatoaguirre24 For temporary fix, I will add collapsedIconProps to Nav. I will propose a permanent way later because now I'm working on mui-formik to integrate Material-UI with formik and it need custom styling solution, so I want both of the project to follow the same way.

**Comment by siriwatknp** [comment]
@elitan what is your use case? there is a props `clipped` to set `Nav` as the same layer as `Header`

**Comment by elitan** [comment]
> @elitan what is your use case? there is a props `clipped` to set `Nav` as the same layer as `Header`

When I use this:
```
  const config = {
    ...standard_config,
    navVariant: {
      xs: 'temporary',
      sm: 'permanent',
      md: 'permanent',
    },
    collapsedBreakpoint: 'md', // collapse between sm and xs
    collapsible: {
      xs: false,
      sm: true,
    },
    clipped: true,
    squeezed: false,
    headerPosition: 'fixed',
  };
```

The `Header` has `z-index: 1201` and the `Nav` has `z-index: 1200`. I was thinking if there was any way to get the `Nav` to be above (higher `z-indez`) than `Header`.

**Comment by siriwatknp** [comment]
@donatoaguirre24 Here it is!
https://siriwatknp.github.io/mui-layout/?path=/story/custom-styles--nav

![image](https://user-images.githubusercontent.com/18292247/62059209-fd64a180-b24c-11e9-8e98-b4bc9f2e4e1a.png)

**Comment by siriwatknp** [comment]
> > @elitan what is your use case? there is a props `clipped` to set `Nav` as the same layer as `Header`
> 
> When I use this:
> 
> ```
>   const config = {
>     ...standard_config,
>     navVariant: {
>       xs: 'temporary',
>       sm: 'permanent',
>       md: 'permanent',
>     },
>     collapsedBreakpoint: 'md', // collapse between sm and xs
>     collapsible: {
>       xs: false,
>       sm: true,
>     },
>     clipped: true,
>     squeezed: false,
>     headerPosition: 'fixed',
>   };
> ```
> 
> The `Header` has `z-index: 1201` and the `Nav` has `z-index: 1200`. I was thinking if there was any way to get the `Nav` to be above (higher `z-indez`) than `Header`.

Yes you can do this if you want to override the styles of Header
```
import { makeStyles } from '@material-ui/styles';

const useAppBarStyles = makeStyles(({ palette }) => ({
  root: {
    zIndex: 1190,
  },
}));

function App() {
  const appBarStyles = useAppBarStyles();
  return (
    <Root>
      <Header classes={appBarStyles} />
    </Root>
  )
}
```
