### ISSUE TITLE
Nav gets temporarily clipped using preset standard

### ISSUE THREAD

**Issue by pillowsoft** [siriwatknp/mui-layout#18]
In 1.2.8, go here: https://siriwatknp.github.io/mui-layout/?path=/story/presets--standard

Refresh the page and the nav will be clipped. Change routes and go back to that page and all is well. An uninitialized variable perhaps?

**Comment by siriwatknp** [comment]
Fixed! in 1.2.9, Thanks for your notice. It was because I changed the `initialAdjustmentHeight` to an object and it didn't work with object at first mount.
