### ISSUE TITLE
Compatibility for material 4.3.0

### ISSUE THREAD

**Issue by ValeFranchi** [siriwatknp/mui-layout#19]
just updated to material-ui 4.3.0 and I'm getting the following issue, maybe was changed something in the useMediaQuery API

![image](https://user-images.githubusercontent.com/21114956/62370822-83147580-b509-11e9-82ab-eeeb4a8bece2.png)

**Comment by siriwatknp** [comment]
@ValeFranchi what `mui-layout` version are you using?
