### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by miguelangeltorresfp** [siriwatknp/mui-layout#24]
It would be great to try this super useful package with next.js to support SSR.
I did it and I fixed this bug:
`ReferenceError: the window is not defined in ... \ mui-layout \ dist \ hooks \ useEventListener.js.11.85`
Simply adding `global.window`

After this fix, it worked perfectly but when refreshing the page in the browser, it first showed the nav (drawer) collapsed and then, once it was completely downloaded, it showed it open.
I don't know if this weird behavior could be easily fixed up to support SSR.

![2](https://user-images.githubusercontent.com/5512161/64138802-ca3ea080-cdfe-11e9-9a62-09f32bdd7ed4.PNG)

![1](https://user-images.githubusercontent.com/5512161/64138759-ab400e80-cdfe-11e9-9a4c-8f51586de910.PNG)

Thank you @siriwatknp for your time and for working in this interesting package.

**Comment by siriwatknp** [comment]
#23 merged
